#import <Foundation/Foundation.h>
#import "SWGInlineResponse200.h"
#import "SWGApi.h"

/**
* <PBXDom API>
* 
*
* OpenAPI spec version: 2.1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGDefaultApi: NSObject <SWGApi>

extern NSString* kSWGDefaultApiErrorDomain;
extern NSInteger kSWGDefaultApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// 
/// Gets `Calls` info. 
///
/// @param rptType Report type. (0 report, 1 widget, 2 chart).
/// @param rptId Report id.
/// @param start Start offset. (optional)
/// @param limit Number of results to return. Max 10K. (optional)
/// @param sortBy Sort column. (optional)
/// @param sortType Sort mode asc/desc. (optional)
/// @param fromDate Start date time. (optional)
/// @param toDate End date time. (optional)
/// @param duration Duration range. (optional)
/// @param phone List of caller phone. (optional)
/// @param phone1 List of dialled phones. (optional)
/// @param co List of trunk/co. (optional)
/// @param ext list of extensions. (optional)
/// @param pbxId list of PBX Ids. (optional)
/// @param callSource list of callsource. (optional)
/// @param callType list of call type signatures.(5 Unanswered Calls, 7 Transfered Calls, 8 Forwarded Calls) (optional)
/// @param direction list of direction.(0 incoming, 1 outgoing, 2 internal) (optional)
/// @param callerName list of caller name. (optional)
/// @param did list of did. (optional)
/// @param dnis list of dnis. (optional)
/// @param acc list of account code. (optional)
/// @param ring Ring range.Seconds unit. (optional)
/// @param cost Cost range. (optional)
/// @param group Department/Group id. (optional)
/// 
///  code:200 message:"Successful response"
///
/// @return NSArray<SWGInlineResponse200>*
-(NSNumber*) callsGetWithRptType: (NSNumber*) rptType
    rptId: (NSNumber*) rptId
    start: (NSNumber*) start
    limit: (NSNumber*) limit
    sortBy: (NSString*) sortBy
    sortType: (NSString*) sortType
    fromDate: (NSString*) fromDate
    toDate: (NSString*) toDate
    duration: (NSNumber*) duration
    phone: (NSString*) phone
    phone1: (NSString*) phone1
    co: (NSString*) co
    ext: (NSString*) ext
    pbxId: (NSNumber*) pbxId
    callSource: (NSNumber*) callSource
    callType: (NSNumber*) callType
    direction: (NSNumber*) direction
    callerName: (NSString*) callerName
    did: (NSString*) did
    dnis: (NSString*) dnis
    acc: (NSString*) acc
    ring: (NSNumber*) ring
    cost: (NSNumber*) cost
    group: (NSNumber*) group
    completionHandler: (void (^)(NSArray<SWGInlineResponse200>* output, NSError* error)) handler;


/// 
/// Gets `Charts` list. 
///
/// 
///  code:200 message:"Successful response"
///
/// @return NSArray<SWGInlineResponse200>*
-(NSNumber*) featuresChartsGetWithCompletionHandler: 
    (void (^)(NSArray<SWGInlineResponse200>* output, NSError* error)) handler;


/// 
/// Gets `Reports` list. 
///
/// 
///  code:200 message:"Successful response"
///
/// @return NSArray<SWGInlineResponse200>*
-(NSNumber*) featuresReportsGetWithCompletionHandler: 
    (void (^)(NSArray<SWGInlineResponse200>* output, NSError* error)) handler;


/// 
/// Gets `Widgets` list. 
///
/// 
///  code:200 message:"Successful response"
///
/// @return NSArray<SWGInlineResponse200>*
-(NSNumber*) featuresWidgetGetWithCompletionHandler: 
    (void (^)(NSArray<SWGInlineResponse200>* output, NSError* error)) handler;



@end
